---
- hosts: databases
  gather_facts: yes
  remote_user: ubuntu
  become: yes
  become_method: sudo

  tasks:
  - name: Add mongo key
    apt_key: 
      url: https://www.mongodb.org/static/pgp/server-6.0.asc
      state: present

  - name: Add mongo repo
    apt_repository:
      repo: "deb https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse"
      state: present
      update_cache: yes

  - name: Upgrade packages
    apt:
      update_cache: yes
      upgrade: yes

  - name: Install mongo
    apt:
      name: mongodb-org
      update_cache: yes

  - name: Run mongod
    systemd:
      name: mongod
      daemon-reload: yes
      enabled: yes
      state: started

  - name: Copy config file
    copy:
      src: /home/vagrant/project/gcpcloud/templates/mongod.conf
      dest: /etc/mongod.conf
    notify: restart mongo

  handlers:
    - name: restart mongo
      systemd:
        name: mongod
        state: restarted

- hosts: database1
  remote_user: ubuntu
  become: yes
  gather_facts: yes
  become_method: sudo

  tasks:
  - name: Set primary from replica
    command: mongosh --eval 'rs.initiate({_id :"rs0",members:[{ _id:0,host:"{{hostvars['database1']['ansible_default_ipv4']['address']}}:27017"},{_id:1,host:"{{hostvars['database2']['ansible_default_ipv4']['address']}}:27017"},{_id:2,host:"{{ hostvars['database3']['ansible_default_ipv4']['address']}}:27017"}]})'
    async: 1000
    poll: 0