---
- hosts: databases
  gather_facts: yes

- hosts: adder
  gather_facts: true
  remote_user: ubuntu
  become: yes
  become_method: sudo
  
  tasks:
    - name: Create src folder
      file:
        path: /home/ubuntu/src
        state: directory
        mode: 0755

    - name: Install pip3
      apt:
        name: python3-pip
        update_cache: yes

    - name: Copy project code
      copy: 
        src: /home/vagrant/project/adder/
        dest: /home/ubuntu/src/

    - name: Copy service unit file
      copy: 
        src: /home/vagrant/project/adder/adder.service
        dest: /etc/systemd/system/adder.service

    - name: Add database ips file
      template:
        src: /home/vagrant/project/gcpcloud/templates/database_ips.j2
        dest: /home/ubuntu/src/database_ips
        mode: 0644

    - name: Install dependencies
      ansible.builtin.pip: 
        chdir: /home/ubuntu/src
        requirements: requirements.txt
      notify: Restart adder

    - name: Run service
      systemd:
        name: adder
        daemon-reload: yes
        enabled: yes
        state: started

  handlers:
    - name: Restart adder
      systemd:
        name: adder
        state: restarted