---
- hosts: adder
  gather_facts: true
  remote_user: ubuntu
  become: yes
  become_method: sudo
  
  tasks:
    - name: Create src folder
      file:
        path: /home/ubuntu/src
        state: directory
        mode: 0755

    - name: Copy project code
      copy: 
        src: /home/vagrant/project/adder/
        dest: /home/ubuntu/src/

    - name: Copy service unit file
      copy: 
        src: /home/vagrant/project/adder/adder.service
        dest: /etc/systemd/system/adder.service

    - name: Install pip3
      apt:
        name: python3-pip
        update_cache: yes

    - name: Install dependencies
      ansible.builtin.pip: 
        chdir: /home/ubuntu/src
        requirements: requirements.txt

    - name: Run service
      systemd:
        name: adder
        daemon-reload: yes
        enabled: yes
        state: started
        masked: no